services:
  api-principal:
    volumes:
      - ./api-principal:/usr/src/app
      - /usr/src/app/node_modules
    command: node src/index.js
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"

  servico-relatorios:
    volumes:
      - ./servico-relatorios:/usr/src/app
      - /usr/src/app/node_modules
    command: node src/index.js
    environment:
      NODE_ENV: development
    ports:
      - "3001:3001"
